### ISSUE TITLE
Quotes changes to often

### ISSUE THREAD

**Issue by Dawid-Ohia** [kim-sardine/statusbar-quotes#5]
Nice plugin for VS Code, very inspiring. I think it would be enough to show one quote for each launch of the application. Unfortunately high frequency of changing the quotes makes it unusable for me.

**Comment by kim-sardine** [comment]
sorry for late reply and thank you for downloading this extension.
showing only one quote in status bar is a good idea I never thought of.
to do that, I think I need to make two changes.
1. 'infinite' option in 'display seconds' (as of now, you can select up to 60 seconds in settings)
2.  new feature to show the entire list and choose one of them.

what do you think?  I'll add these to todo list first. thanks again.

**Comment by kim-sardine** [comment]
hey, you can set `statusbar-quotes.display-seconds` to `0` to see only one quote.
and I've added new feature to change quote randomly.
I think these changes can solve your problem.

please reopen it anytime if you want.
